configurationDefinitions:
  - platform: HOST
    type: AgentConfig
    version: 1.0.0
    format: yml
    operatingSystem: LINUX
  - platform: HOST
    type: AgentConfig
    version: 1.0.0
    format: yml
    operatingSystem: WINDOWS
