name: Prerelease pipeline

on:
  release:
    types:
      - prereleased
    tags:
      - 'v*'

jobs:
  pre-release:
    uses: newrelic/coreint-automation/.github/workflows/reusable_pre_release.yaml@v3
    with:
      tag: ${{ github.event.release.tag_name }}
      integration: "apache"
      upload_fips_packages: true
      dest_prefix: fips-test-nri-apache-rahul/
      test_package: false
    secrets: inherit
